server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/dev/inflearn-study/cloud-yml
#        git:
#          default-label: cloud-discoveryservice
#          uri: https://github.com/newzinee/inflearn-study.git
#          searchPaths: cloud-yml

# actuator
management:
  endpoints:
    web:
      exposure:
        include: "health, busrefresh"