spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}da891181cc6882909a84c52980115d64f36c46662a1444bc962ece77b5966e76'
    driver-class-name: org.h2.Driver

token:
  expiration_time: 864000000 #ms
  secret: user_token_native_application_changed_#12

gateway:
  ip: 192.168.75.135